FROM node AS build
WORKDIR /web
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --prod

FROM nginx
COPY --from=build /web/dist/angular-15-crud /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]